package sbs1

// FROM http://woodair.net/sbs/article/barebones42_socket_data.htm
// Message types
// There are six message types - MSG, SEL, ID, AIR, STA, CLK. Most data from aircraft is contained in the MSG lines whilst the other types are triggered by user input or system settings. The MSG data was inhibited with a five minute delay in BaseStation versions prior to 1.2.3.145 but from this version onwards is in real time.
// ID   Type                     Description
// SEL  SELECTION CHANGE MESSAGE // Generated when the user changes the selected aircraft in BaseStation.
// ID   NEW ID MESSAGE           // Generated when an aircraft being tracked sets or changes its callsign.
// AIR  NEW AIRCRAFT MESSAGE     // Generated when the SBS picks up a signal for an aircraft that it isn't currently tracking.
// STA  STATUS CHANGE MESSAGE    // Generated when an aircraft's status changes according to the time-out values in the Data Settings menu.
// CLK  CLICK MESSAGE            // Generated when the user double-clicks (or presses return) on an aircraft // (i.e. to bring up the aircraft details window).
// MSG  TRANSMISSION MESSAGE     // Generated by the aircraft. There are eight different MSG types.

// Transmission messages (MSG) from aircraft may be one of eight types:
// ID     Type                           CORRESPONDING ADSB   Description
// MSG,1  ES Identification and Category DF17 BDS 0,8
// MSG,2  ES Surface Position Message    DF17 BDS 0,6         Triggered by nose gear squat switch.
// MSG,3  ES Airborne Position Message   DF17 BDS 0,5
// MSG,4  ES Airborne Velocity Message   DF17 BDS 0,9
// MSG,5  Surveillance Alt Message       DF4, DF20            Triggered by ground radar. Not CRC secured.
//                                                            MSG,5 will only be output if  the aircraft has previously sent a MSG,1, 2, 3, 4 or 8 signal.
// MSG,6  Surveillance ID Message        DF5, DF21            Triggered by ground radar. Not CRC secured.
//                                                            MSG,6 will only be output if  the aircraft has previously sent a  MSG,1, 2, 3, 4 or 8 signal.
// MSG,7  Air To Air Message             DF16                 Triggered from TCAS. MSG,7 is now included in the SBS socket output.
// MSG,8  All Call Reply                 DF11                 Broadcast but also triggered by ground radar

// Field Data
// Each of the above message types may contain up to 22 data fields separated by commas. These fields are:

// Field 1:	 Message type 	 (MSG, STA, ID, AIR, SEL or CLK)
// Field 2:	 Transmission Type 	 MSG sub types 1 to 8. Not used by other message types.
// Field 3:	 Session ID 	 Database Session record number
// Field 4:	 AircraftID 	 Database Aircraft record number
// Field 5:	 HexIdent 	 Aircraft Mode S hexadecimal code
// Field 6:	 FlightID 	 Database Flight record number
// Field 7:	 Date message generated 	  As it says
// Field 8:	 Time message generated 	  As it says
// Field 9:	 Date message logged 	  As it says
// Field 10: Time message logged 	  As it says
//
// The above basic data fields are standard for all messages (Field 2 used only for MSG).
//
// The fields below contain specific aircraft information.
// Field 11: Callsign		An eight digit flight ID - can be flight number or registration (or even nothing).
// Field 12: Altitude		Mode C altitude. Height relative to 1013.2mb (Flight Level). Not height AMSL..
// Field 13: GroundSpeed	Speed over ground (not indicated airspeed)
// Field 14: Track			Track of aircraft (not heading). Derived from the velocity E/W and velocity N/S
// Field 15: Latitude 	 	North and East positive. South and West negative.
// Field 16: Longitude 	 	North and East positive. South and West negative.
// Field 17: VerticalRate	64ft resolution
// Field 18: Squawk			Assigned Mode A squawk code.
// Field 19: Alert (Squawk change) 	 Flag to indicate squawk has changed.
// Field 20: Emergency		Flag to indicate emergency code has been set
// Field 21: SPI (Ident) 	Flag to indicate transponder Ident has been activated.
// Field 22: IsOnGround 	Flag to indicate ground squat switch is active
//
// Notes (Courtesy of Edgy):
//
// The socket data outputs a -1 for true, and a 0 for false. Neither means it is not used.
//
// Field 11 (Callsign) is an 8 character (6 bit ASCII subset) field. In BaseStation a NULL is shown as a '@' which is ASCII for NULL. In the cockpit it is just a space on the transponder window, but is sent as a NULL. Therefore, if a crew enter eight spaces in the cockpit this will show in BaseStation as @@@@@@@@.
//
// Field 12 (Altitude) can be 25ft or 100 foot resolution. Mode-C is 100 ft, but many aircraft today send out 25 ft resolution to be able to fly in Europe IFR (RVSM) space. BaseStation only displays Barometer altitude but in the data are HAE (height above ellipsoid), which is sent as the difference between GPS altitude and barometric altitude.

// MLAT OUTPUT
// https://github.com/mutability/mlat-server/blob/bee59806af1fda9728489279a96f0f5ac56abfe7/mlat/server/output.py#L148C1-L148C196
// TEMPLATE = 'MSG,{mtype},1,1,{addr:06X},1,{rcv_date},{rcv_time},{now_date},{now_time},{callsign},{altitude},{speed},{heading},{lat},{lon},{vrate},{squawk},{fs},{emerg},{ident},{aog}\n'  # noqa
